### ISSUE TITLE
pickles:

### ISSUE THREAD

**Issue by ditzh** [biplavc/multi_UAV_Age_7#1]
/home/biplav/AoI/UAV_results/multi_UAV_Age_7/paper_results/exp1/   thanks for your works very much! let me learn the AOI and UAV, and i want also do something about UAV, and your work give me the guild work. so i would mind you may give those pickles in exp1 and exp2 ... thanks again.

**Comment by biplavc** [comment]
the pickle files are used to store the variables generated as a result of the experiment. You can also run the code and the pickle files will get generated automatically once the simulation ends.
