### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by Prince-Kr-Sharma** [biplavc/multi_UAV_Age_7#2]
Hi can you please provide details about how can I run this all code step by step

**Comment by biplavc** [comment]
what is the error?

**Comment by Prince-Kr-Sharma** [comment]
while running main_tf I'm getting this error:-
<ipython-input-81-18eb64add974> in do_scheduling(deployment, I, scheduler)
    120         t1 = time.time()
    121         #with tf.device('/CPU:0'):
--> 122         random_overall[I], random_final[I], random_all_actions[I] = random_scheduling(I, drones_coverage, folder_name, deployment, packet_update_loss, packet_sample_loss, periodicity)
    123         t2 = time.time()
    124         print("random for ", I, " users took ", t2-t1, " seconds to complete", file=open(folder_name + "/results.txt", "a"), flush=True)

~\Desktop\UAV\random_scheduling.ipynb in random_scheduling(I, drones_coverage, folder_name, deployment, packet_update_loss, packet_sample_loss, periodicity)

NameError: name 'random_episodes' is not defined

and if I'm commenting out the scheduler == "random" then it works but the problem is it's not dumping any data in the RP folder inside the models' folder

can you please tell me how should I run all the code so that I can get the desired result like yours? that would be great help

**Comment by biplavc** [comment]
1. There should not be any problem with `random_episodes` as it is defined in tf_enviornment.py, so try to see why this is happening. Check if the command imports work. And do not run the jupyter notebooks, just run main_tf.py. The jupyter notebooks were just to try out different isolated commands for personal use.
2. Dumping should work fine if you make the error in the above point correct. Dumping will work from both main_tf.py and random_scheduling.py

**Comment by Prince-Kr-Sharma** [comment]
Hi everything is working fine, can you guide me on how scratch_period.ipynb, scratch_additional.ipynb, scratch_user_dist.ipynb will work for generating graphs, I'm facing issue with the path which u have given:
path = "/home/biplav/AoI/UAV_results/multi_UAV_Age_7/paper_results/additional/exp9/"
can you help me with this path ?

**Comment by biplavc** [comment]
Those are just too plot the pickle files, you c use them the way you want. Better to directly use tensor board.
